import os
import time
import requests
from io import BytesIO
from PIL import Image, ImageGrab
import pytesseract
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from docx import Document
from docx.shared import Inches as DocxInches, Pt as DocxPt
from brain.llm_chat import ask_gemini
from voice.tts import speak

import urllib.parse
import requests

def download_internet_image(query: str) -> str:
    """Fetches a relevant public image using DuckDuckGo search."""
    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
        search_url = f"https://duckduckgo.com/i.js?q={urllib.parse.quote(query)}"
        res = requests.get(search_url, headers=headers, timeout=5)
        
        if res.status_code == 200:
            data = res.json()
            results = data.get("results", [])
            if results:
                image_url = results[0]["image"]
                img_res = requests.get(image_url, headers=headers, timeout=10)
                if img_res.status_code == 200:
                    file_path = f"web_image_{int(time.time())}.jpg"
                    with open(file_path, "wb") as f:
                        f.write(img_res.content)
                    return file_path
    except Exception as e:
        print(f"[Warning] Image download fallback triggered: {e}")
    return ""

def handle_office_command(query: str, log_fn, lang: str) -> bool:
    # 1. AI-Powered PowerPoint with Custom Themes, Web Text & Web Images
    if any(k in query for k in ["create ppt on", "make presentation on", "generate ppt"]):
        topic = query.replace("create ppt on", "").replace("make presentation on", "").replace("generate ppt", "").strip()
        if not topic:
            topic = "Artificial Intelligence"

        log_fn(f"[Office]: Generating presentation on '{topic}' with web data and images...")
        speak(f"Creating presentation on {topic} with text and internet images.", lang)

        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        # Slide 1: Title Slide with Custom Dark Theme
        slide1 = prs.slides.add_slide(prs.slide_layouts[6])
        background = slide1.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(15, 23, 42)  # Dark Blue

        txBox = slide1.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11.33), Inches(2))
        tf = txBox.text_frame
        p = tf.paragraphs[0]
        p.text = topic.upper()
        p.font.size = Pt(44)
        p.font.bold = True
        p.font.color.rgb = RGBColor(255, 255, 255)

        p2 = tf.add_paragraph()
        p2.text = "Generated by AI Voice Assistant"
        p2.font.size = Pt(20)
        p2.font.color.rgb = RGBColor(56, 189, 248)

        # Fetch AI summary text for content slide
        prompt = f"Provide 3 bullet points explaining key concepts of {topic}. Keep each point under 15 words."
        ai_summary = ask_gemini(prompt)

        # Slide 2: Content Slide with Text + Downloaded Web Image
        slide2 = prs.slides.add_slide(prs.slide_layouts[6])
        
        # Add Text Frame on Left
        tx_box2 = slide2.shapes.add_textbox(Inches(0.8), Inches(1), Inches(6.5), Inches(5.5))
        tf2 = tx_box2.text_frame
        tf2.word_wrap = True
        p_title = tf2.paragraphs[0]
        p_title.text = f"Key Highlights: {topic.title()}"
        p_title.font.size = Pt(28)
        p_title.font.bold = True

        for line in ai_summary.split("\n"):
            if line.strip():
                p_bullet = tf2.add_paragraph()
                p_bullet.text = line.strip()
                p_bullet.font.size = Pt(18)
                p_bullet.space_before = Pt(10)

        # Download & Insert Web Image on Right Side
        img_path = download_internet_image(topic)
        if img_path and os.path.exists(img_path):
            slide2.shapes.add_picture(img_path, Inches(7.8), Inches(1.5), width=Inches(4.8))

        filename = f"PPT_{topic.replace(' ', '_')}.pptx"
        prs.save(filename)
        log_fn(f"[Office]: Presentation saved to {filename}")
        speak("PowerPoint created with text content and web images.", lang)
        return True

    # 2. AI Word Document with Headings, Internet Images & Text Insertion
    elif any(k in query for k in ["create document on", "make word file on", "write report on"]):
        topic = query.replace("create document on", "").replace("make word file on", "").replace("write report on", "").strip()
        if not topic:
            topic = "Technology Innovation"

        log_fn(f"[Office]: Writing Word document on '{topic}'...")
        speak(f"Writing Word report on {topic}.", lang)

        doc = Document()
        
        # Heading
        heading = doc.add_heading(f"Report: {topic.title()}", level=0)
        if heading.runs:
            heading.runs[0].font.size = DocxPt(24)
        
        # Fetch detailed content from Gemini
        ai_content = ask_gemini(f"Write a detailed introductory overview about {topic} in 2 paragraphs.")
        doc.add_paragraph(ai_content)

        # Fetch and Insert Image from Web
        img_path = download_internet_image(topic)
        if img_path and os.path.exists(img_path):
            doc.add_heading("Visual Reference", level=1)
            doc.add_picture(img_path, width=DocxInches(5.0))
            doc.add_paragraph(f"Figure 1: Internet image reference for {topic}.")

        filename = f"Report_{topic.replace(' ', '_')}.docx"
        doc.save(filename)
        log_fn(f"[Office]: Word document saved as '{filename}'")
        speak("Word document generated with text and web images.", lang)
        return True

    # 3. Create Custom Text File with Internet Summary
    elif any(k in query for k in ["create text file about", "save info on"]):
        topic = query.replace("create text file about", "").replace("save info on", "").strip()
        info = ask_gemini(f"Summarize the main facts about {topic} in 150 words.")
        
        filename = f"{topic.replace(' ', '_')}_info.txt"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"SUBJECT: {topic.upper()}\n")
            f.write("="*40 + "\n\n")
            f.write(info)

        log_fn(f"[Office]: Text file saved as '{filename}'")
        speak(f"Information saved to {filename}.", lang)
        return True

    # 4. Screen OCR: Read & Summarize On-Screen Text
    elif any(k in query for k in ["read screen", "ocr screen", "summarize screen"]):
        log_fn("[OCR]: Capturing and reading on-screen text...")
        speak("Capturing screen for optical character recognition.", lang)
        
        screenshot = ImageGrab.grab()
        extracted_text = pytesseract.image_to_string(screenshot).strip()
        
        if extracted_text:
            log_fn(f"[OCR Extracted Text]:\n{extracted_text[:300]}...")
            summary = ask_gemini(f"Summarize this text extracted from screen: {extracted_text[:1500]}")
            log_fn(f"[OCR Summary]: {summary}")
            speak(f"Screen text summary: {summary}", lang)
        else:
            speak("No readable text found on the screen.", lang)
        return True

    return False